# Generated by Django 4.1.1 on 2022-10-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_option',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
