# Generated by Django 4.1.1 on 2022-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_shippingaddress_payment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBackURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CallbackMetadata', models.CharField(max_length=600)),
                ('CheckoutRequestID', models.CharField(max_length=600)),
                ('MerchantRequestID', models.CharField(max_length=600)),
                ('ResultCode', models.CharField(max_length=600)),
                ('ResultDesc', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPaymentAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
