# Generated by Django 4.1.1 on 2022-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_item_images_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='img1', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='img', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='img', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
