# Generated by Django 4.1.1 on 2022-11-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_callbackurl_gallery_mpesapaymentapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='items', to='commerce.orderitem'),
        ),
    ]
