# Generated by Django 4.1.1 on 2022-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_rename_images_item_image_item_image1_item_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(upload_to='products'),
        ),
    ]
