# Generated by Django 4.1.1 on 2022-10-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_shippingaddress_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='shipping_address',
        ),
    ]
